name: Go 1.15

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: macos-10.15
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
  
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 10.0.0
  
    - name: Install github.com/goplusjs/gopherjs
      run: |
        go get -v github.com/goplusjs/gopherjs
        cd $HOME/go/src/github.com/goplusjs/gopherjs
        npm install # Install our (dev) dependencies from package.json.
        cd node-syscall && ../node_modules/node-gyp/bin/node-gyp.js rebuild rebuild && mkdir -p ~/.node_libraries && cp build/Release/syscall.node ~/.node_libraries/syscall.node
    - name: Test gopherjs
      run: |
        cd $HOME/go/src/github.com/goplusjs/gopherjs
        ulimit -s 10000 && gopherjs test --minify -v --short $(go list std | grep -v -f .std_test_pkg_exclusions)
